import type { Metadata } from "next";
import "./globals.css";
import navbar from "@/components/productCard";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <header>
        <navbar></navbar>
      </header>
      
      
      <body>
        {children}
      </body>
    </html>
  );
}
