import type { Metadata } from "next";
import { roboto, crimson_text } from '../constants/fonts'
import "./globals.css";
import HamburgerMenu from '../components/hamburgerMenu'



export const metadata : Metadata = {
    title: 'rest-menu-app',
    description:'Generated by Next.js'
}

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    
    return (
      <html lang="en" className={`${roboto.variable} ${crimson_text.variable}`}>
        <body>

          <header>
          <div className=" bg-gray-100 flex flex-col md:flex-row items-center justify-center">
            <HamburgerMenu />
          </div>
          </header>
          <main >{children}</main>
          <footer>Footer Area</footer>
        </body>
      </html>
    )
  }