import type { Metadata } from "next";
import "./globals.css";

export const metadata : Metadata = {
    title: 'rest-menu-app',
    description:'Generated by Next.js'
}

export default function RootLayout({
    children,
  }: {
    children: React.ReactNode
  }) {
    return (
      <html lang="en">
        <body>
          {/* Layout UI */}
          <main>{children}</main>
        </body>
      </html>
    )
  }